package cli

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// runInit inspects a repository and writes a commented starter .memlint.toml.
//
// This is the only write memlint performs, anywhere: one new file, created
// with O_EXCL so an existing config can never be overwritten, not even by a
// race. check remains strictly read-only.
//
// Rules are enabled on evidence only. An index file that exists gets
// [pointers]; observed .DS_Store or *.tmp files get [junk]. Everything else
// is emitted as a commented example, because enabling an invariant nobody
// depends on is noise, and noise is how a checker gets ignored.
func runInit(args []string, stdout, stderr io.Writer) int {
	switch {
	case len(args) > 0 && (args[0] == "-h" || args[0] == "--help"):
		fmt.Fprint(stdout, usageText)
		return ExitClean
	case len(args) > 1:
		fmt.Fprintf(stderr, "memlint: unexpected argument %q\n", args[1])
		fmt.Fprint(stderr, usageText)
		return ExitUsage
	}

	root := "."
	if len(args) == 1 {
		root = args[0]
	}
	info, err := os.Stat(root)
	if err != nil {
		fmt.Fprintf(stderr, "memlint: cannot read target %s: %v\n", root, err)
		return ExitUsage
	}
	if !info.IsDir() {
		fmt.Fprintf(stderr, "memlint: target %s is not a directory\n", root)
		return ExitUsage
	}

	ev := inspect(root)
	content, enabled := renderConfig(ev)

	cfgPath := filepath.Join(root, ".memlint.toml")
	// O_EXCL makes "refuse to overwrite" atomic rather than check-then-write.
	f, err := os.OpenFile(cfgPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		if os.IsExist(err) {
			fmt.Fprintf(stderr, "memlint: %s already exists; init refuses to overwrite it\n", cfgPath)
		} else {
			fmt.Fprintf(stderr, "memlint: cannot write %s: %v\n", cfgPath, err)
		}
		return ExitUsage
	}
	if _, err := f.WriteString(content); err != nil {
		f.Close()
		fmt.Fprintf(stderr, "memlint: writing %s: %v\n", cfgPath, err)
		return ExitUsage
	}
	if err := f.Close(); err != nil {
		fmt.Fprintf(stderr, "memlint: writing %s: %v\n", cfgPath, err)
		return ExitUsage
	}

	switch enabled {
	case 0:
		fmt.Fprintf(stdout, "memlint: wrote %s (no rules enabled — uncomment the examples inside as invariants emerge)\n", cfgPath)
	default:
		fmt.Fprintf(stdout, "memlint: wrote %s (%s enabled) — review it, then run: memlint check\n",
			cfgPath, pluralRules(enabled))
	}
	return ExitClean
}

// evidence is what one read-only pass over the repository turned up.
type evidence struct {
	indexFiles []string // existing top-level index files, candidate [pointers] sources
	mdRoots    []string // top-level dirs that contain markdown, candidate [pointers] roots
	dsStore    bool     // a .DS_Store exists somewhere in the tree
	tmpFiles   bool     // a *.tmp exists somewhere in the tree
}

// indexCandidates are the files agent runtimes conventionally read as memory
// indexes. Only ones that actually exist are configured.
var indexCandidates = []string{"MEMORY.md", "CLAUDE.md", "AGENTS.md"}

func inspect(root string) evidence {
	var ev evidence

	for _, name := range indexCandidates {
		if info, err := os.Stat(filepath.Join(root, name)); err == nil && info.Mode().IsRegular() {
			ev.indexFiles = append(ev.indexFiles, name)
		}
	}

	roots := map[string]bool{}
	// WalkDir does not follow symlinked directories, so a symlink cannot pull
	// content from outside the tree into the evidence.
	filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil // unreadable corners are check's problem, not init's
		}
		if d.IsDir() {
			if p != root && (d.Name() == ".git" || strings.HasPrefix(d.Name(), ".")) {
				return fs.SkipDir
			}
			return nil
		}
		switch {
		case d.Name() == ".DS_Store":
			ev.dsStore = true
		case strings.HasSuffix(d.Name(), ".tmp"):
			ev.tmpFiles = true
		}
		if strings.EqualFold(filepath.Ext(d.Name()), ".md") {
			rel, err := filepath.Rel(root, p)
			if err != nil {
				return nil
			}
			rel = filepath.ToSlash(rel)
			if i := strings.Index(rel, "/"); i > 0 {
				roots[rel[:i]] = true
			}
		}
		return nil
	})
	ev.mdRoots = make([]string, 0, len(roots))
	for r := range roots {
		ev.mdRoots = append(ev.mdRoots, r)
	}
	sort.Strings(ev.mdRoots)
	return ev
}

// renderConfig produces the generated file and the number of enabled rules.
// The output must always pass config.Load — that property is pinned by test.
func renderConfig(ev evidence) (string, int) {
	var b strings.Builder
	enabled := 0

	b.WriteString(`# .memlint.toml — generated by memlint init from an inspection of this
# repository. Review before trusting: only rules with observed evidence are
# enabled; the rest are commented examples. A section's presence is what
# enables its rule. Docs: https://github.com/frankbesch/memlint#rules

`)

	if len(ev.indexFiles) > 0 && len(ev.mdRoots) > 0 {
		enabled++
		b.WriteString("# Repo-path references in these files must resolve to files that exist.\n")
		b.WriteString("[pointers]\n")
		b.WriteString("files = " + tomlList(ev.indexFiles) + "\n")
		b.WriteString("# A reference is checked only when its first path segment is a root here.\n")
		b.WriteString("roots = " + tomlList(ev.mdRoots) + "\n\n")
	}

	if ev.dsStore || ev.tmpFiles {
		enabled++
		var globs []string
		if ev.dsStore {
			globs = append(globs, ".DS_Store")
		}
		if ev.tmpFiles {
			globs = append(globs, "*.tmp")
		}
		b.WriteString("# Files matching these globs were found in the tree and should not be here.\n")
		b.WriteString("[junk]\n")
		b.WriteString("globs = " + tomlList(globs) + "\n\n")
	}

	b.WriteString(`# --- no evidence found for the rules below; uncomment and adapt to enable ---

# Files or directories that must stay byte-identical:
# [mirrors]
# pairs = [["CLAUDE.md", "docs/CLAUDE.md"]]

# Logs that may only grow, compared against git HEAD:
# [append_only]
# files = ["memory/decisions.md"]

# Agent-owned regions whose markers must stay well-formed:
# [blocks]
# files = ["CLAUDE.md"]
# start = "<!-- AGENT:START -->"
# end = "<!-- AGENT:END -->"

# Files no agent may ever have written, checked against full git history:
# [human_brief]
# files = ["INSTRUCTIONS.md"]
# agent_authors = ["noreply@anthropic.com"]

# Notes that must stay under a token budget:
# [tokens]
# watch = ["memory/*.md"]
# budget = 2000
# limit = 4000   # optional hard tier: past this is RED, not YELLOW
`)

	return b.String(), enabled
}

// tomlList renders a TOML array of strings. %q quoting is a valid TOML basic
// string for repository-relative paths.
func tomlList(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func pluralRules(n int) string {
	if n == 1 {
		return "1 rule"
	}
	return fmt.Sprintf("%d rules", n)
}
